### ISSUE TITLE
Fix issue with conda-forge builds

### ISSUE THREAD

**Issue by analog-cbarber** [analog-garage/mkdocstrings-python-xref#35]
The conda-forge builds have been failing for a long time and no new versions have been merged.

I think the problem has something to do with hatchling and the contents of the sdist from pypi...

**Comment by analog-cbarber** [comment]
I think that 1.16.1 will work on conda-forge, but will wait for the merge request....

Also deleted the sdists from pypi from 1.6.1 through 14.1 because they were not built correctly.

**Comment by analog-cbarber** [comment]
This has been fixed.

For future reference, the problem was that the following section in the pyproject.toml file was causing hatch to generate an sdist with the package in the top-level rather than the `src/` dir:

```toml
[tool.hatch.build.targets.sdist]
packages = [
    "src/mkdocstrings_handlers",
]
```
